# You can use the variables below with ${} in your script and filepath_to_upload
#  BACKUP_ID
#  BACKUP_NAME
#  TEMP_DIR (without trailing slash at the end)
#  And all environment variables set

# Example of tar gzipping a file and uploading it to the backup:
#  tar -czf test.tar.gz test1.log test2/test2.log
jobs:
  - name: nextcloud-backup
    # every day at 12:00
    schedule: "0 12 * * *"
    script:
      - cd ${TEMP_DIR}
      - mysqldump -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h ${MYSQL_HOST} nextcloud > out.sql
      - tar -czf nextcloud.tar.gz out.sql
    filepath_to_upload: ${TEMP_DIR}/nextcloud.tar.gz

  - name: ghost-backup
    schedule: "0 12 * * *"
    script:
      - cd ${TEMP_DIR}
      - mysqldump -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h ${MYSQL_HOST} ghost > out.sql
      - tar -czf ghost.tar.gz out.sql
    filepath_to_upload: ${TEMP_DIR}/ghost.tar.gz
